### ISSUE TITLE
Отзыв о работе ефикатора

### ISSUE THREAD

**Issue by eshlykov** [dima74/Wikipedia-Efication#1]
Здравствуйте, Дмитрий!

Спасибо за Ваш скрипт. Работает он неплохо, однако бывают некоторые проблемы:  
1. Сообщение "Ошибка: $.scrollTo не определено." встречается достаточно часто (примерно каждую 3-4 страницу). Обычно она пропалает после обновления страницы, но [вот отсюда](https://ru.wikipedia.org/wiki/Даян-Омбо) уже не помогало.
2. Иногда очень долго тянется отправление изменений, причем, похоже, это не связано с ее объемом и количеством замен. Встречается каждую 5-6 страницу.
3. Хотелось бы, что правки Вашим скриптом обозначались через малозначимые изменения. Не хочется, чтобы когда люди смотрели мой вклад, они видели 70% ефикации скриптом. Содержательные правки теряются.
4. Для принятия и отмены правки требуется переключение на английскую раскладку, так что заниматься чем-то другим параллельно становится неудобно.

Но зато обнаружение замен работает превосходно: за 20 с лишним правок ни разу не пришлось отклонять замену.

**Comment by dima74** [comment]
Ага,

1. исправлено в e61a6f4e5908327f313205d84b2674fba70a72de
2. Не воспроизводится
3. Исправлено в 84212ba4f146d382e2e4e933447c02905f603546
4. Исправлено в 2e2ad3706d9ee7760dd14c8d9fce4f6dcea74b3a
