### ISSUE TITLE
Кнопка Ёфикатора в редакторе

### ISSUE THREAD

**Issue by nzeemin** [dima74/Wikipedia-Efication#2]
Помимо вызова Ёфикатора в вите закладки, было бы здорово иметь возможность использования Ёфикатора из стандартного веб-редактора. Типично что помимо ёфикации хочется также нажать Викификатор, и не хочется разделять это на две отдельные правки.

**Comment by dima74** [comment]
Привет) Да, это хорошее предложение. Смогу это реализовать я, к сожалению, не в ближайшее время.

**Comment by dima74** [comment]
@nzeemin [появилась новая версия скрипта](https://ru.wikipedia.org/wiki/Участник:Дима74/Скрипт-Ёфикатор), в которой доступна ёфикация в редакторе. Если ещё интересует эта возможность, можешь посмотреть
